server:
  start: -0.99
  end: 1
  step: 0.99
  num_of_samples: 3
  wait_for: 600

simulation:
  display:
    fps: 120
    window_size: 512
    use_pygame: false
    print_results: false

  particles:
    radius: 3.0
    num: 1000
    start_pos: !!python/tuple [256, 256]

  system:
    push_out_tries: 10
    max_steps: 4000
    # remove NaN's from walking population after:
    regen_after_updates: 200

  planes:
    min_box_size: 0.015625
    particle_collision_plane_size: 32

  simulation:
    step_strength: 2
