# window_size: 1024
window_size: 512
particle_radius: 3.0
num_of_particles: 1000

fps: 120
min_box_size: 0.015625

start_pos: !!python/tuple [256, 256]
epsilon: !!python/float 1e-10
push_out_tries: 10
use_pygame: false
print_results: false
max_steps: 4000

# multiple of 'particle_radius' which will be used while checking collision; min = 0
radius_check: 2

# remove NaN's from walking population after:
regen_after_updates: 200
step_strength: 2
memory: 0
