# window_size: 256
window_size: 1024
point_radius: 5.0
num_of_points: 2000
fps: 120
min_box_size: 128
start_pos: !!python/tuple [512, 512]
epsilon: !!python/float 1e-10
push_out_tries: 10

# multiple of 'point_radius' which will be used while checking collision; min = 0
radius_check: 2