window_size: 512
particle_radius: 3.0
num_of_particles: 1000
fps: 120
min_box_size: 0.015625

start_pos: !!python/tuple [256, 256]
push_out_tries: 10
use_pygame: true
print_results: true
max_steps: 4000

# remove NaN's from walking population after:
regen_after_updates: 200
step_strength: 2
memory: -0.99
particle_plane_size: 32