# window_size: 256
window_size: 1024
point_radius: 5.0
num_of_points: 2000
fps: 120
min_box_size: 0.015625
second_min_box_size: 0.03125

# 1/2 = 0.5
# 1/4 = 0.25
# 1/8 = 0.125
# 1/16 = 0.0625
# 1/32 = 0.03125
# 1/64 = 0.015625

start_pos: !!python/tuple [512, 512]
epsilon: !!python/float 1e-10
push_out_tries: 10
use_pygame: true

# multiple of 'point_radius' which will be used while checking collision; min = 0
radius_check: 2
